### ISSUE TITLE
Entidades (Visual Studio)

### ISSUE THREAD

**Issue by Lisyty** [Lisyty/Grupo-1-DS#4]

**Comment by Dltr17** [comment]
Buen día, entrego las clases de acuerdo con el diagrama, las cuales deberán ser agregadas a la carpeta Entidad, de la capa de Dominio (*.App.Dominio), así mismo apenas este configurado el nombre dentro del archivo se debe actualizar la lineal 3 la palabra "proyecto" por le nombre del proyecto, quedo atento a comentarios.  
[Entidades.zip](https://github.com/Lisyty/Grupo-1-DS/files/9416327/Entidades.zip)
